### PR TITLE
Fix for block maps with null lines

### PR DESCRIPTION
**Pull request by henrytseng**

### CODE REVIEW

**Comment by FunkyloverOne** [comment]
@henrytseng is this a fix for https://github.com/samu/blocky/issues/20 issue?
If so, is there any way to use it in my atom, without waiting for repo maintainer to merge your PR?

**Comment by henrytseng** [comment]
It is a fix.  You can simply use the Github url in your Gemfile.

**Comment by waldnzwrld** [comment]
I can confirm that this resolves the error when switching projects / branches / opening atom

**Comment by FunkyloverOne** [comment]
Me too, working flawlessly almost half year for me :)

**Comment by waldnzwrld** [comment]
@samu I noticed there hasn't been a commit to master since around Jan of last year. Is there anyway we can get this PR merged ?

**Comment by samu** [comment]
released with `v0.11.0`

**Comment by waldnzwrld** [comment]
🙇 you rock 🎸

**Pull request merged**
